services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432" # using port 5433 on host to avoid conflict with locally running servers
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 3000:80 # local port 80 to virtual port 80 for nginx
    depends_on:
      - backend
    # for local hosting uncomment this and comment out the nginx service
    # volumes:
    #   - ./frontend:/usr/src/app
    #   - /usr/src/app/node_modules
    # ports:
    #   - "5173:3000"

volumes:
  db_data:
